name: Workflow for Codecov

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Set up all three available os to run tests on
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    # Use python 3.6
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.6'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.6
      
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "requirements.txt"

      - name: Generate coverage report
        run: |
          pip install coverage
          coverage run -m unittest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true
